### ISSUE TITLE
I compiled it but...

### ISSUE THREAD

**Issue by Skeagle137** [bonimy/MushROMs#21]
It forms a .dll file, but what do you do with that? doesn't it need an executable file?

**Comment by bonimy** [comment]
The code is still in "upload" phase. So there's currently nothing it does. I need to add unit tests for everything I plan to upload, so it's going to take some time. What interests did you have in the project?

**Comment by Skeagle137** [comment]
oh I was going to try and make a rom hack for super mario all stars

**Comment by bonimy** [comment]
Oh. Unfortunately we're not at that state yet. You are free to star the project to follow its progress though. I'll make a note to update the documentation to reflect this isn't release ready.

**Comment by Skeagle137** [comment]
Ok I wasn't really expecting it to be finished yet, so i'll just star this project.
